### ISSUE TITLE
Book and code file differences

### ISSUE THREAD

**Issue by Konnor5092** [PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET#14]
I'm currently on chapter 7 of the book and so far the code files don't always match the content in the book. As a result I'm struggling to add the code myself whilst working through the chapters as it is either already there in the previous chapters code file, or it has been implemented in a way that doesn't match the book.

For example, chapter 6, page 150 introduces us to the api section.... 

![image](https://user-images.githubusercontent.com/18048889/74826439-846d8a00-5303-11ea-82a6-3e3258542e03.png)

but this section has already been implemented in the chapter 5 code file [here](https://github.com/PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET-Core/blob/master/Chapter05/Marketplace/Contracts/ClassifiedAds.cs) 

Another example is in chapter 8, page 219 which mentions the `IClassifiedAdRepository` repository for the first time.....

![image](https://user-images.githubusercontent.com/18048889/74826921-5472b680-5304-11ea-984e-d47cc2d818f5.png)

Yet this already has an implementation in the chapter 5 code file [here](https://github.com/PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET-Core/blob/master/Chapter05/Marketplace/ClassifiedAdRepository.cs) 

Another example is the `RetryingCommandHandler<T>` described in chapter 6. This is nowhere in the chapter 6 folder.

And so on....

As someone completely new to DDD who hasn't built much software before, I had hoped I could use the code files as a starting point for each chapter and add the code from the book. After finishing the chapter the solution would then be identical to that chapters code file. Unfortunately this doesn't appear to be the case.

**Comment by alexeyzimarev** [comment]
I will have a look through the code samples, but please keep in mind that each chapter has a complete running code. For example, if there's no API in the Chapter 5 code, the whole thing is kind of meaningless, because you can't try out things. You need an API to execute those operations anyway. So, some things will always be already implemented before being mentioned in the book.

Concerning the retrying handler, I had no intention to put all ideas from the book into the code and vice versa. That particular example is mentioned in the book as an example of composition and it shouldn't be hard to implement one.

**Comment by Konnor5092** [comment]
Okay. Sounds like this book is probably beyond my level of experience. If chapter 5 in the book doesn't implement any running code (apart from tests) I wouldn't expect the equivalent chapter 5 code file to either. There are also references to raverndb in the chapter 5 code file which is not touched on until chapter 8 in the book. 

If only the code in the book is used, should it produce a running application at the end of each chapter?

**Comment by alexeyzimarev** [comment]
Well, I didn't have intentions to write a C# book, there're better books for that. My thought was to give readers some ideas on how certain tactical DDD patterns can be implemented in code. The code for each chapter in the book repository contains most of the code from the chapter itself, but it could contain _more_ code just to make the whole thing work. Make no mistake, it is neither a tutorial book nor a cookbook. It is a book about Domain-Driven Design with some practical examples of how certain things can be implemented.

**Comment by alexeyzimarev** [comment]
Just to finalise this discussion, the book code is much harder to fix and adjust since it's printed on paper. However, the code in this repository is changing when people discover bugs and issues.

We are considering to release an updated version of the book where I plan to address some of the comments. But again, code snippets in the book are serving the purpose of giving examples. The repository is a necessary and integral part of the book, so it contains working code for each chapter and therefore might be ahead of the text. Otherwise, the text would get polluted by repeated code (which already happened, a necessary evil).
